# Generated by Django 3.2.6 on 2022-06-25 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_testcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestComment',
        ),
    ]
